"""Generate docs/data-dictionary.md from the governance config.

The dictionary is written once, in governance/config/tables.json, and applied to
Unity Catalog by the governance notebook. This script renders the same file as
markdown so a BI or AI engineer can read it without a workspace login. CI runs it
and fails if the committed copy is stale, which is what keeps the two in step.

    python tools/data_dictionary.py
"""

from __future__ import annotations

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
CONFIG = ROOT / "governance" / "config" / "tables.json"
OUTPUT = ROOT / "docs" / "data-dictionary.md"

LAYER_BLURB = {
    "bronze": "Raw source data with audit columns. Not for consumption — read Silver or Gold instead.",
    "silver": "Cleaned, typed, de-duplicated entities. History where it matters (SCD Type 2).",
    "gold": "The star schema and the wide views. This is what BI tools and AI agents should query.",
}


def render(config: dict) -> str:
    lines = [
        "# Data dictionary",
        "",
        "<!-- Generated by tools/data_dictionary.py from governance/config/tables.json. Do not edit by hand. -->",
        "",
        f"Owner: {'`' + config['owner'] + '`' if config.get('owner') else 'set per environment in `governance/config/tables.json`'}.",
        "Every comment and tag below is applied to Unity Catalog by the `governance` task on each run,",
        "so the catalog and this page cannot drift apart.",
        "",
    ]

    for layer in ["bronze", "silver", "gold"]:
        tables = [t for t in config["tables"] if t["schema"] == layer]
        if not tables:
            continue
        lines += [f"## {layer.title()}", "", LAYER_BLURB[layer], ""]

        for table in sorted(tables, key=lambda t: t["name"]):
            lines += [f"### `{layer}.{table['name']}`", "", table.get("comment", "_No description._"), ""]

            if table.get("primary_key"):
                lines.append(f"- **Primary key:** {', '.join(f'`{c}`' for c in table['primary_key'])}")
            for fk in table.get("foreign_keys", []):
                columns = ", ".join(f"`{c}`" for c in fk["columns"])
                lines.append(f"- **Foreign key:** {columns} → `{fk['references']}` ({', '.join(f'`{c}`' for c in fk['referenced_columns'])})")
            if table.get("pii_columns"):
                lines.append(f"- **PII:** {', '.join(f'`{c}`' for c in table['pii_columns'])} — tagged `pii=true`, restricted by grants")
            if table.get("tags"):
                lines.append("- **Tags:** " + ", ".join(f"`{k}={v}`" for k, v in sorted(table["tags"].items())))
            lines.append("")

            comments = table.get("column_comments", {})
            if comments:
                lines += ["| Column | Meaning |", "| --- | --- |"]
                lines += [f"| `{column}` | {text} |" for column, text in comments.items()]
                lines.append("")

    lines += ["## Audit columns", "", "Present on Bronze and Silver tables.", "", "| Column | Meaning |", "| --- | --- |"]
    lines += [f"| `{column}` | {text} |" for column, text in config["audit_column_comments"].items()]
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    config = json.loads(CONFIG.read_text())
    OUTPUT.write_text(render(config))
    print(f"wrote {OUTPUT.relative_to(ROOT)} ({len(config['tables'])} objects)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
